insert into stores (store_id, name, address) values (1, 'Toys', '5 Comanche Way');
insert into stores (store_id, name, address) values (2, 'Shoes', '30 Warrior Parkway');
insert into stores (store_id, name, address) values (3, 'Beauty', '21013 Orin Road');
insert into stores (store_id, name, address) values (4, 'Industrial', '76 Brickson Park Terrace');
insert into stores (store_id, name, address) values (5, 'Jewelry', '3 Di Loreto Place');
insert into stores (store_id, name, address) values (6, 'Books', '23394 Debs Trail');
insert into stores (store_id, name, address) values (7, 'Movies', '5 Arkansas Drive');
insert into stores (store_id, name, address) values (8, 'Electronics', '8 Hazelcrest Crossing');
insert into stores (store_id, name, address) values (9, 'Industrial', '61 Vermont Circle');
insert into stores (store_id, name, address) values (10, 'Jewelry', '16 Annamark Alley');
